In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from category_encoders import TargetEncoder
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import classification_report

In [34]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [35]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [36]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [37]:
print(df["TotalCharges"].dtype)

object

In [38]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors = "coerce")
df["TotalCharges"] = df["TotalCharges"].fillna(0)
df["TotalCharges"] = df["TotalCharges"].round().astype(int)

In [39]:
df["MonthlyCharges"] = df["MonthlyCharges"].astype(int)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   int64
 19  TotalCharges      7043 non-null   int64
 20  Churn             7043 non-null   object
dtypes: int64(4), object(17)
memory usage: 1.1+ MB

In [41]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29,30,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56,1890,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53,108,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42,1841,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70,152,Yes

In [42]:
x = df.drop(columns = "Churn")
y = df.Churn

In [43]:
num_cols = x.select_dtypes(include = "number").columns
cat_cols = x.select_dtypes(include = "object").columns

In [44]:
xtrain , xtest, ytrain, ytest = train_test_split(x,y,random_state = 42, train_size = 0.8)

In [45]:
cat_cols.nunique()

16

In [46]:
cat_cols

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [47]:
preprocessing = ColumnTransformer(
    transformers = [
        ("scaler",StandardScaler(),num_cols),
        ("onehot",OneHotEncoder(),['gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod']),
        ("target",TargetEncoder(),"customerID")
    ]
)

In [48]:
main_pipe = Pipeline(
    steps = [
        ("pre",preprocessing),
        ("model",KNeighborsClassifier())
    ]
)

In [49]:
main_pipe.fit(xtrain,ytrain)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')),
                                                 ('onehot', OneHotEncoder(),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod']),
                                                 ('target', TargetEncoder(),
                                                  'customerID')])),
                ('model', KNeighborsClassifier())])

In [50]:
grid_cv = GridSearchCV(
    estimator = main_pipe,
    param_grid = {
        "model__n_neighbors" : [3,7,25,27,29,38],
        "model__metric" : ["manhattan","euclidean"]
    },
    cv = 5,
    n_jobs = -1,
    verbose = 1
)

In [51]:
grid_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

c:\Users\bthar\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.73908631 0.76890218 0.78966999 0.78753981 0.78789553 0.78807094]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('pre',
                                        ColumnTransformer(transformers=[('scaler',
                                                                         StandardScaler(),
                                                                         Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')),
                                                                        ('onehot',
                                                                         OneHotEncoder(),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'InternetService',
                                                                          'OnlineSecurity',
                                                                          'OnlineBackup',
                                                                          'DeviceProtection',
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod']),
                                                                        ('target',
                                                                         TargetEncoder(),
                                                                         'customerID')])),
                                       ('model', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'model__metric': ['manhattan', 'euclidean'],
                         'model__n_neighbors': [3, 7, 25, 27, 29, 38]},
             verbose=1)

In [52]:
results = grid_cv.cv_results_
pd.DataFrame(results)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__metric,param_model__n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.063968,0.010613,0.023645,0.005427,manhattan,3,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
1,0.074889,0.005476,0.021476,0.004114,manhattan,7,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
2,0.069752,0.007906,0.017424,0.001606,manhattan,25,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
3,0.069519,0.007746,0.018662,0.001647,manhattan,27,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4,0.075770,0.013067,0.023049,0.005845,manhattan,29,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
5,0.073236,0.006780,0.020927,0.003928,manhattan,38,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
6,0.068144,0.012166,0.081445,0.009227,euclidean,3,"{'model__metric': 'euclidean', 'model__n_neigh...",0.741792,0.739130,0.736469,0.726708,0.751332,0.739086,0.007967,6
7,0.087125,0.003242,0.101465,0.007424,euclidean,7,"{'model__metric': 'euclidean', 'model__n_neigh...",0.776398,0.789707,0.751553,0.763088,0.763766,0.768902,0.013040,5
8,0.073688,0.012290,0.106721,0.004935,euclidean,25,"{'model__metric': 'euclidean', 'model__n_neigh...",0.789707,0.790594,0.793256,0.784383,0.790409,0.789670,0.002906,1
9,0.085277,0.010930,0.114824,0.004369,euclidean,27,"{'model__metric': 'euclidean', 'model__n_neigh...",0.791482,0.793256,0.790594,0.775510,0.786856,0.787540,0.006368,4
10,0.077417,0.008479,0.096469,0.017683,euclidean,29,"{'model__metric': 'euclidean', 'model__n_neigh...",0.785271,0.798580,0.783496,0.780834,0.791297,0.787896,0.006354,3
11,0.082710,0.014325,0.079521,0.005784,euclidean,38,"{'model__metric': 'euclidean', 'model__n_neigh...",0.780834,0.804791,0.789707,0.785271,0.779751,0.788071,0.009074,2

In [53]:
grid_cv.best_params_

{'model__metric': 'euclidean', 'model__n_neighbors': 25}

In [54]:
main_pipe2 = Pipeline(
    steps = [
        ("pre",preprocessing),
        ("model",KNeighborsRegressor())
    ]
)

In [55]:
grid_cv2 = GridSearchCV(
    estimator = main_pipe2,
    param_grid = {
        "model__n_neighbors" : [3,7,25,27,29,38],
        "model__metric" : ["manhattan","euclidean"]
    },
    cv = 5,
    n_jobs = -1,
    verbose = 1
)

In [56]:
grid_cv2.fit(xtrain,ytrain)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

c:\Users\bthar\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('pre',
                                        ColumnTransformer(transformers=[('scaler',
                                                                         StandardScaler(),
                                                                         Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')),
                                                                        ('onehot',
                                                                         OneHotEncoder(),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'InternetService',
                                                                          'OnlineSecurity',
                                                                          'OnlineBackup',
                                                                          'DeviceProtection',
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod']),
                                                                        ('target',
                                                                         TargetEncoder(),
                                                                         'customerID')])),
                                       ('model', KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'model__metric': ['manhattan', 'euclidean'],
                         'model__n_neighbors': [3, 7, 25, 27, 29, 38]},
             verbose=1)

In [57]:
results2 = grid_cv2.cv_results_
pd.DataFrame(results2)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__metric,param_model__n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.049795,0.001332,0.306732,0.041549,manhattan,3,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,0.067358,0.006276,0.350587,0.036395,manhattan,7,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,0.086482,0.005940,0.440325,0.055156,manhattan,25,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,0.106128,0.008225,0.486049,0.040838,manhattan,27,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,0.112593,0.016881,0.451828,0.058430,manhattan,29,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
5,0.108320,0.015163,0.414386,0.047409,manhattan,38,"{'model__metric': 'manhattan', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
6,0.121205,0.005691,0.150829,0.020142,euclidean,3,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
7,0.126830,0.017291,0.138603,0.017970,euclidean,7,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
8,0.115439,0.010448,0.155366,0.012511,euclidean,25,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
9,0.129459,0.008061,0.153352,0.017753,euclidean,27,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
10,0.108661,0.007052,0.122371,0.016016,euclidean,29,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
11,0.085058,0.018101,0.090080,0.007394,euclidean,38,"{'model__metric': 'euclidean', 'model__n_neigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [58]:
grid_cv2.best_params_

{'model__metric': 'manhattan', 'model__n_neighbors': 3}

In [59]:
ytrain_pred = grid_cv.predict(xtrain)
print(classification_report(ytrain,ytrain_pred))

              precision    recall  f1-score   support

          No       0.87      0.89      0.88      4138
         Yes       0.68      0.62      0.64      1496

    accuracy                           0.82      5634
   macro avg       0.77      0.75      0.76      5634
weighted avg       0.82      0.82      0.82      5634

In [61]:
ytest_pred = grid_cv.predict(xtest)
print(classification_report(ytest,ytest_pred))

              precision    recall  f1-score   support

          No       0.86      0.89      0.87      1036
         Yes       0.66      0.59      0.62       373

    accuracy                           0.81      1409
   macro avg       0.76      0.74      0.75      1409
weighted avg       0.81      0.81      0.81      1409

In [ ]:
ytrain_pred = grid_cv.predict(xtrain)
print(classification_report(ytrain,ytrain_pred))